server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch-study?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        use-new-id-generator-mappings: false
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hivernate.type: trace